# Importing Libraries & Loading Data

In [975]:
import pandas as pd

As was determined by inspecting files in Excel, different datasets have headers in different rows. Therefore, `header` is set variably to correctly display column names.

In [976]:
# economy
birth_rate = pd.read_excel("data/raw/economy/birth_rate.xlsx", header=3)
employed_population = pd.read_excel("data/raw/economy/employed_population.xls", header=3)
gdp_per_capita = pd.read_excel("data/raw/economy/gdp_per_capita.xlsx", header=2)
monthly_salaries = pd.read_excel("data/raw/economy/monthly_salaries.xlsx", header=4)
unemployment = pd.read_excel("data/raw/economy/unemployment.xlsx", header=4)
production = pd.read_excel("data/raw/economy/production.xls", header=3)

# education
educational_facilities = pd.read_excel("data/raw/education/educational_facilities.xls", header=3)
instructors = pd.read_excel("data/raw/education/instructors.xlsx", header=3)
students = pd.read_excel("data/raw/education/students_of_schools_and_unis.xls", header=3)

Now let's take a look at each of the datasets one by one.

In [977]:
birth_rate

,Көрсөткүчтөрдүн аталыштары,Наименование показателей,Items,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024 1
0,Кыргыз Республикасы,Кыргызская Республика,Kyrgyz Republic,149612.0,154918.0,155520.0,161813.0,163452.0,158160.0,153620.0,171149.0,173484.0,158112.0,150164.0,150225.0,145977.0,140419.0
1,Баткен облусу,Баткенская область,Batken Region,13449.0,13800.0,14294.0,14722.0,15330.0,14325.0,13476.0,14882.0,15480.0,14144.0,13056.0,13656.0,14683.0,14086.0
2,Жалал-Абад облусу,Джалал-Абадская область,Jalal-Abad Region,30139.0,30416.0,30341.0,31633.0,31912.0,29844.0,29843.0,31433.0,32251.0,30061.0,28358.0,28195.0,30838.0,29669.0
3,Ысык-Көл облусу,Иссык-Кульская область,Issyk-Kul Region,11188.0,11320.0,10745.0,10853.0,11246.0,11520.0,10824.0,11242.0,10557.0,9938.0,9119.0,9029.0,10408.0,9861.0
4,Нарын облусу,Нарынская область,Naryn Region,7203.0,7114.0,6906.0,6634.0,6536.0,6858.0,6410.0,6622.0,6034.0,5701.0,5090.0,4734.0,7278.0,6898.0
5,Ош облусу,Ошская область,Osh Region,33600.0,34450.0,35057.0,36867.0,39188.0,36145.0,35181.0,35983.0,35305.0,32716.0,28148.0,29813.0,35125.0,31339.0
6,Талас облусу,Таласская область,Talas Region,7335.0,7105.0,6750.0,6724.0,6614.0,6404.0,6032.0,6413.0,6007.0,5785.0,5213.0,5153.0,6145.0,5683.0
7,Чүй облусу,Чуйская область,Chui Region,20293.0,21826.0,21806.0,22540.0,22355.0,22964.0,21787.0,24845.0,24617.0,21710.0,19849.0,19876.0,21670.0,17944.0
8,Бишкек ш.,г.Бишкек,Bishkek City,20808.0,22257.0,22971.0,24398.0,22928.0,22673.0,22364.0,27727.0,29625.0,26143.0,27486.0,27460.0,12980.0,15783.0
9,Ош ш.,г.Ош,Osh City,5597.0,6630.0,6650.0,7442.0,7343.0,7427.0,7703.0,12002.0,13608.0,11914.0,13845.0,12309.0,6850.0,9156.0
10,1 Кыргыз Республикасындагы административдик-ай...,1 С учетом изменений по итогам административно...,1 Taking into account changes resulting from t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [978]:
employed_population

,Көрсөткүчтөрдүн аталышы,Наименование показателей,Items,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Кыргыз Республикасы,Кыргызская Республика,Kyrgyz Republic,2277.693355,2286.4,2263.0,2302.704407,2352.100000,2363.7,2351.2,2382.5,2442.7,2445.2,2537.9,2581.1,2656.2,2756.0
1,Баткен облусу,Баткенская область,Batken oblast,165.022923,160.433783,153.4,158.555934,181.116151,186.4,184.8,178.4,175.4,165.4,176.3,177.1,168.3,170.0
2,Жалал-Абад облусу,Джалал-Абадская область,Djalal-Abad oblast,423.843932,429.544989,432.5,421.207704,408.714248,402.7,380.1,359.0,381.7,383.2,396.3,427.0,398.5,415.8
3,Ысык-Көл облусу,Иссык-Кульская область,Issyk-Kul oblast,174.881789,174.940351,163.0,166.298438,170.058722,165.2,158.2,162.9,162.2,163.7,173.5,169.9,176.5,179.6
4,Нарын облусу,Нарынская область,Naryn oblast,85.438553,85.335298,77.8,79.530871,79.151950,84.6,87.7,89.6,90.9,90.4,95.6,97.3,110.2,116.6
5,Ош облусу,Ошская область,Osh oblast,589.964334,586.947943,518.5,529.745407,543.594946,550.4,537.3,569.1,608.5,607.9,632.0,631.3,622.5,616.9
6,Талас облусу,Таласская область,Talas oblast,103.260473,102.883384,105.8,115.714272,118.600836,117.4,111.3,108.8,106.0,110.4,114.9,119.8,119.3,121.9
7,Чуй облусу,Чуйская область,Chui oblast,350.192665,353.529778,332.4,333.028401,332.336360,317.6,333.8,348.0,347.2,343.1,357.1,351.6,372.8,407.4
8,Бишкек ш.,г.Бишкек,Bishkek city,385.088686,392.781225,391.3,404.644472,424.205459,442.0,456.5,461.2,463.6,472.4,482.3,492.6,557.1,593.9
9,Ош ш.,г.Ош,Osh city,…,…,88.2,93.978908,94.294976,97.5,101.5,105.4,107.1,108.8,109.9,114.6,131.0,134.1
10,1 үй-чарбалардын бюджеттерине жана жумушчу күч...,1по данным интегрированного выборочного обслед...,1according to an integrated sample survey of h...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [979]:
gdp_per_capita

,Көрсөткүчтөрдүн аталыштары,Наименование показателей,Items,2020,2021,2022,2023,2024
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Калктын адам башына ички дүң продукт (миң сом),Валовой внутренний продукт на душу населения (...,Gross domestic product per capita (thous. soms),95.1,114.3,146.3,187.9,219.2
2,Калктын адам башына ички дүң продукт (АКШ долл...,Валовой внутренний продукт на душу населения (...,Gross domestic product per capita (U.S. dollar),1230.3,1350.7,1740.1,2137.2,2513.4
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,*алдына ала маалыматтар,* предварительные данные,* preliminary data,NaN,NaN,NaN,NaN,NaN

In [980]:
monthly_salaries

,Көрсөткүчтөрдүн аталыштары,Наименование показателей,Items,2006,2007,2008,2009,2010,2011,2012,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Кыргыз Республикасы,Кыргызская Республика,Kyrgyz Republic,3270.0,3866.0,5378.0,6161.0,7189.0,9304.0,10726.0,...,13483.0,14847.0,15670.0,16427.0,17232.0,18940.0,19330.0,26540.0,31604.0,36047.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Баткен облусу,Баткенская область,Batken oblast,2266.0,2658.0,3703.0,4012.0,4651.0,6531.0,8206.0,...,9468.0,10093.0,10486.0,11026.0,11583.0,13017.0,13010.0,20439.0,25554.0,26662.0
4,Жалал-Абад облусу,Джалал-Абадская область,Jalal-Abat oblast,2511.0,2914.0,4467.0,5166.0,5986.0,8149.0,9818.0,...,12035.0,13277.0,13939.0,14600.0,15843.0,17580.0,17478.0,24869.0,28764.0,31229.0
5,Ысык-Көл облусу,Иссык-Кульская область,Yssyk-Kul oblast,4383.0,5048.0,6762.0,8538.0,9676.0,13667.0,14119.0,...,17979.0,19800.0,21543.0,21397.0,22208.0,26860.0,30172.0,34669.0,38743.0,41084.0
6,Нарын облусу,Нарынская область,Naryn oblast,2571.0,2853.0,4476.0,4741.0,5770.0,8445.0,9991.0,...,12724.0,13991.0,14340.0,14925.0,15945.0,18071.0,17941.0,26031.0,33011.0,35205.0
7,Ош облусу,Ошская область,Osh oblast,1569.0,2170.0,2981.0,3279.0,3719.0,6419.0,7639.0,...,8708.0,9950.0,10180.0,10307.0,11368.0,12712.0,12557.0,19762.0,23134.0,25200.0
8,Талас облусу,Таласская область,Talas oblast,1944.0,2361.0,3590.0,4412.0,5155.0,7036.0,8453.0,...,9882.0,10625.0,11295.0,12511.0,12969.0,16156.0,16400.0,25092.0,30689.0,34068.0
9,Чүй облусу,Чуйская область,Chui oblast,2858.0,3577.0,4499.0,4862.0,5736.0,7207.0,8657.0,...,11288.0,12554.0,13391.0,14114.0,14724.0,16051.0,15958.0,21641.0,25562.6,27819.0
10,Бишкек ш.,г.Бишкек,Bishkek city,4376.0,5072.0,6958.0,8041.0,9351.0,11336.0,12796.0,...,16526.0,18185.0,19336.0,20517.0,21082.0,22677.0,23085.0,30757.0,37454.7,44074.0
11,Ош ш.,г.Ош,Osh city,2733.0,3298.0,4599.0,5153.0,6104.0,7394.0,9864.0,...,11894.0,13008.0,13274.0,13804.0,14866.0,15726.0,15674.0,23459.0,26960.5,30039.0
12,*Без учета малых предприятий,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [981]:
unemployment

,Көрсөткүчтөрдүн аталыштары,Наименование показателей,Items,2006,2007,2008,2009,2010,2011,2012,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Кыргыз Республикасы,Кыргызская Республика,Kyrgyz Republic,8.3,8.2,8.2,8.415442,8.643742,8.530152,8.4,...,7.600000,7.2,6.9,6.2,5.5,5.8,5.3,4.9,4.1,3.7
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Баткен облусу,Баткенская область,Batken oblast,11.6,10.3,11.1,10.197395,10.593518,10.585734,10.8,...,10.912793,10.2,9.9,9.0,8.2,7.4,6.6,6.1,5.9,5.7
4,Жалал-Абад облусу,Джалал-Абадская область,Jalal-Abat oblast,6.4,6.8,6.9,6.960941,7.846714,8.152282,8.4,...,7.656621,7.5,7.2,6.2,5.5,11.0,11.8,10.8,8.2,7.1
5,Ысык-Көл облусу,Иссык-Кульская область,Yssyk-Kul oblast,7.7,7,7.2,9.384832,10.217816,9.65921,9.6,...,9.068651,8.9,8.7,8.4,7.9,7.4,6.3,5.5,5.1,4.5
6,Нарын облусу,Нарынская область,Naryn oblast,11,11.1,11.2,10.00545,10.344614,10.300299,10.2,...,9.286726,9.0,8.8,8.8,8.3,7.3,6.3,5.8,5.1,4.8
7,Ош облусу,Ошская область,Osh oblast,5,5.4,5.5,6.631339,6.627287,6.630795,6.8,...,6.027853,5.5,5.1,4.2,3.5,2.6,1.9,1.5,1.4,0.9
8,Талас облусу,Таласская область,Talas oblast,5.1,5.1,5.4,4.902786,5.060168,5.043066,4.1,...,3.259938,2.8,2.5,2.5,2.5,2.6,2.6,2.3,2.0,2.0
9,Чүй облусу,Чуйская область,Chui oblast,13.1,13,12.7,10.349741,10.24284,9.919452,9.9,...,8.592704,8.4,8.1,7.3,6.6,6.1,5.3,4.6,4.1,3.7
10,Бишкек ш.,г.Бишкек,Bishkek city,9.3,8.7,8.6,10.154086,9.994021,9.579866,8.7,...,8.053710,7.7,7.3,6.6,5.9,5.0,4.1,4.0,3.5,3.5
11,Ош ш.,г.Ош,Osh city,…,…,…,…,…,…,…,...,3.903298,3.6,3.5,3.0,2.4,2.8,2.8,2.6,2.1,1.9
12,1үй-чарбалардын бюджеттерине жана жумушчу күчү...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1 По данным интегрированного выборочного обс...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1Аccording to an integrated sample survey of h...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [982]:
production

,Көрсөткүчтөрдүн аталыштары,Наименование показателей,Items,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Кыргыз Республикасы,Кыргызская Республика,Kyrgyz Republic,164361.1,137229.2,169829.4,171108.9,181026.7,209812.0000,237225.3,257348.5,283971.7079,325090.1,370533.8,435815.6,495344.0,599755.2
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Баткен облусу,Баткенская область,Batken oblast,3536.7,4545.4,5929.7,5284.1,4821.6,4359.2825,4744.5,2810.9,2975.2513,3110.9,4349.4,4741.7,6428.9,9100.3
3,Жалал-Абад облусу,Джалал-Абадская область,Djalal-Abad oblast,14325.3,15468.9,13033.2,13300.1,18115.1,20087.8535,25006.5,26808.0,28711.3886,28306.0,36609.2,45724.3,51861.7,58354.1
4,Ыссык-Көл облусу,Ыссык-Кульская область,Issyk-Kul oblast,44257.9,27232.2,41723.6,40993.1,42198.1,51129.4198,52416.4,49965.4,62280.2412,78831.2,74737.6,87613.5,81350.6,96703.6
5,Нарын облусу,Нарынская область,Naryn oblast,1177.2,1245.2,1257.9,1590.7,1977.7,2332.3707,2388.2,2622.8,2870.4549,3206.6,3293.6,4322.8,4965.0,7028.6
6,Ош облусу,Ошская область,Osh oblast,2852.3,3006.0,3389.0,3581.3,3735.8,4074.7310,4772.2,9621.1,10385.5737,9457.8,13516.8,14596.5,17317.6,18474.2
7,Талас облусу,Таласская область,Talas oblast,750.5,773.0,844.0,981.1,895.9,949.0357,1316.7,1290.9,1578.3340,1899.9,15128.8,22789.9,26240.3,34164.8
8,Чүй облусу,Чуйская область,Chui oblast,65011.2,49000.7,67331.9,67873.8,70836.5,86977.5784,102403.7,116570.2,128102.5328,155656.3,167981.4,192441.8,222615.1,258345.1
9,Бишкек ш.,г. Бишкек,Bishkek Сity,30269.4,33454.8,33743.9,34639.4,35081.7,36458.3747,39876.9,42840.7,42291.9887,40053.9,48978.7,57148.9,77162.4,106682.8
10,Ош ш.,г. Ош,Osh Сity,2180.6,2503.0,2576.2,2865.3,3364.3,3443.3136,4300.2,4818.5,4775.9427,4567.5,5938.3,6436.2,7402.4,10901.7

In [983]:
educational_facilities

,Көрсөткүчтөрдүн аталышы,Наименование показателей,Items,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Мектепке чейинки уюмдар,Дошкольные организации,Pre-school institutions,741,819,927,1062,1186,1296,1390,1497,1617,1648,1712,1834,1912,1997
1,Жалпы билим берүү уюмдары,Общеобразовательные организации,General education schools,2204,2201,2207,2205,2218,2236,2262,2265,2283,2296,2333,2350,2377,2394
2,Башталгыч (1 - 4-класстар),Начальные (1 - 4 классы),Elementary (1 - 4 grades),125,118,115,115,115,122,132,130,131,133,135,135,133,130
3,Негизги (1 - 9-класстар),Основные (1 - 9 классы),Junior (5 - 9 grades),202,222,202,203,200,196,192,195,201,199,210,224,227,242
4,Орто (1 - 11-класстар),Средние (1 - 11 классы),High (10 - 11 grades),1857,1841,1871,1868,1884,1900,1920,1922,1931,1946,1970,1973,1999,2004
5,Атайын муктаждыгы бар балдар,Для детей со специальными нуждами,For children with learning disabilities,20,20,19,19,19,18,18,18,20,18,18,18,18,18
6,Башталгыч кесиптик билим берүү уюмдары,Образовательные организации начального профес...,Vocational schools,109,110,110,101,101,101,99,99,99,99,99,100,100,98
7,Орто кесиптик билим берүү уюмдары,Образовательные организации среднего професси...,Secondary special educational institutions,126,132,131,129,130,139,145,148,144,138,141,142,135,134
8,Жогорку кесиптик билим берүү уюмдары,Образовательные организации высшего профессио...,Higher educational institutions,54,54,55,53,52,50,51,51,55,57,60,61,58,57

In [984]:
instructors

,Көрсөткүчтөрдүн аталышы,Наименование показателей,Items,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Мектепке чейинки уюмдар,Дошкольные организации,Pre-school institutions,3647,4053,4492,5116,5693,6414,7151,7694,8312,8301,8785,9796,10426,11959
1,Жалпы билим беруучу уюмдар,Общеобразовательные организации,General education schools,75502,75656,74407,72928,75529,79472,80773,77639,78552,82055,82724,89962,93531,93696
2,Атайын муктаждыгы бар балдар учун,Для детей со специальными нуждами,For children with learning disabilities,660,606,472,510,497,516,519,509,518,541,536,569,577,568
3,Баштапкы кесиптик билим берүү уюмдары,Образовательные организации начального профес...,Vocational schools,3875,3811,3293,3404,3448,3584,3520,3079,3311,3418,3477,3140,3182,3631
4,Орто кесиптик билим берүү уюмдары,Образовательные организации среднего професси...,Secondary special educational institutions,5590,6343,7230,7547,6725,7427,7496,7179,7181,7299,7857,8447,8684,9550
5,Жогорку кесиптик билим беріі уюмдары,Образовательные организации высшего профессио...,Higher educational institutions,12830,12633,14059,13155,14233,10812,12145,11665,12160,12197,13006,12039,12322,12570

In [985]:
students

,Көрсөткүчтөрдүн аталышы,Наименование показателей,Items,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Негизги уюмду (9-класс) бүтүштү,Окончили основную организацию (9 классов),Secondary shcools (9 grades),100.9,94.4,92.1,91.4,90.7,89.0,89.9,91.8,96.7,102.4,102.2,106.2,114.4,121.5
1,Орто (толук) уюмду (11-класс) бүтүштү,Окончили среднюю (полную) организацию (11 кла...,High shcools (11 grades),56.7,55.9,52.8,50.0,51.8,53.4,52.8,49.8,49.6,50.6,54.1,58.8,57.1,55.9
2,Башталгыч кесиптик билим берүү уюмдары,Образовательные организации начального профес...,Vocational schools,28.1,25.4,27.5,25.5,25.7,24.8,29.8,33.3,27.9,24.9,23.6,22.4,20.2,26.0
3,Орто кесиптик билим берүү уюмдары,Образовательные организации среднего професси...,Secondary special educational institutions,15.5,16.4,17.9,23.0,27.1,28.7,27.0,27.6,28.0,28.4,29.1,27.8,27.9,32.9
4,Жогорку кесиптик билим берүү уюмдары,Образовательные организации высшего профессио...,Higher educational institutions,41.8,41.7,41.3,40.8,41.7,52.8,48.9,33.1,33.6,35.0,35.9,35.1,40.2,41.2

# Data Cleaning Strategy

After initial inspection of the files, datasets share similar column structures, contain NaN values, duplicate columns in different languages, and other issues.

- Retain only columns with English names, as the project will be presented in English.
- Remove NaN values that cannot be recovered or are meaningless, along with metadata.
- Transpose each dataset so that year columns become the index, and categories become columns.
- Standardize numeric values to a consistent format (e.g., accounting for metadata indicating values in thousands or tens of thousands).
- Address remaining problems on a case-by-case basis as they arise.

The objective is to merge all data into a single solid dataset. To achieve this, each dataset must first be cleaned individually. The merging process will be addressed subsequently.

# birth_rate

In [986]:
birth_rate

,Көрсөткүчтөрдүн аталыштары,Наименование показателей,Items,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024 1
0,Кыргыз Республикасы,Кыргызская Республика,Kyrgyz Republic,149612.0,154918.0,155520.0,161813.0,163452.0,158160.0,153620.0,171149.0,173484.0,158112.0,150164.0,150225.0,145977.0,140419.0
1,Баткен облусу,Баткенская область,Batken Region,13449.0,13800.0,14294.0,14722.0,15330.0,14325.0,13476.0,14882.0,15480.0,14144.0,13056.0,13656.0,14683.0,14086.0
2,Жалал-Абад облусу,Джалал-Абадская область,Jalal-Abad Region,30139.0,30416.0,30341.0,31633.0,31912.0,29844.0,29843.0,31433.0,32251.0,30061.0,28358.0,28195.0,30838.0,29669.0
3,Ысык-Көл облусу,Иссык-Кульская область,Issyk-Kul Region,11188.0,11320.0,10745.0,10853.0,11246.0,11520.0,10824.0,11242.0,10557.0,9938.0,9119.0,9029.0,10408.0,9861.0
4,Нарын облусу,Нарынская область,Naryn Region,7203.0,7114.0,6906.0,6634.0,6536.0,6858.0,6410.0,6622.0,6034.0,5701.0,5090.0,4734.0,7278.0,6898.0
5,Ош облусу,Ошская область,Osh Region,33600.0,34450.0,35057.0,36867.0,39188.0,36145.0,35181.0,35983.0,35305.0,32716.0,28148.0,29813.0,35125.0,31339.0
6,Талас облусу,Таласская область,Talas Region,7335.0,7105.0,6750.0,6724.0,6614.0,6404.0,6032.0,6413.0,6007.0,5785.0,5213.0,5153.0,6145.0,5683.0
7,Чүй облусу,Чуйская область,Chui Region,20293.0,21826.0,21806.0,22540.0,22355.0,22964.0,21787.0,24845.0,24617.0,21710.0,19849.0,19876.0,21670.0,17944.0
8,Бишкек ш.,г.Бишкек,Bishkek City,20808.0,22257.0,22971.0,24398.0,22928.0,22673.0,22364.0,27727.0,29625.0,26143.0,27486.0,27460.0,12980.0,15783.0
9,Ош ш.,г.Ош,Osh City,5597.0,6630.0,6650.0,7442.0,7343.0,7427.0,7703.0,12002.0,13608.0,11914.0,13845.0,12309.0,6850.0,9156.0
10,1 Кыргыз Республикасындагы административдик-ай...,1 С учетом изменений по итогам административно...,1 Taking into account changes resulting from t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [987]:
clean_birth_rate = birth_rate.copy()

clean_birth_rate = clean_birth_rate.drop(columns=["Көрсөткүчтөрдүн аталыштары", "Наименование показателей"])
clean_birth_rate.dropna(inplace=True) # the only row with NaN is metadata, so we can safely drop it
clean_birth_rate = clean_birth_rate.set_index('Items').T

# Convert index to datetime year and fix '2024 1' to 2024
clean_birth_rate.index = pd.to_datetime(clean_birth_rate.index.astype(str).str.replace(' 1', ''), format='%Y').year
clean_birth_rate.index.name = 'Year'

# Remove the 'Items' name from columns
clean_birth_rate.columns.name = None

In [988]:
clean_birth_rate

,Kyrgyz Republic,Batken Region,Jalal-Abad Region,Issyk-Kul Region,Naryn Region,Osh Region,Talas Region,Chui Region,Bishkek City,Osh City
Year,,,,,,,,,,
2011,149612.0,13449.0,30139.0,11188.0,7203.0,33600.0,7335.0,20293.0,20808.0,5597.0
2012,154918.0,13800.0,30416.0,11320.0,7114.0,34450.0,7105.0,21826.0,22257.0,6630.0
2013,155520.0,14294.0,30341.0,10745.0,6906.0,35057.0,6750.0,21806.0,22971.0,6650.0
2014,161813.0,14722.0,31633.0,10853.0,6634.0,36867.0,6724.0,22540.0,24398.0,7442.0
2015,163452.0,15330.0,31912.0,11246.0,6536.0,39188.0,6614.0,22355.0,22928.0,7343.0
2016,158160.0,14325.0,29844.0,11520.0,6858.0,36145.0,6404.0,22964.0,22673.0,7427.0
2017,153620.0,13476.0,29843.0,10824.0,6410.0,35181.0,6032.0,21787.0,22364.0,7703.0
2018,171149.0,14882.0,31433.0,11242.0,6622.0,35983.0,6413.0,24845.0,27727.0,12002.0
2019,173484.0,15480.0,32251.0,10557.0,6034.0,35305.0,6007.0,24617.0,29625.0,13608.0
2020,158112.0,14144.0,30061.0,9938.0,5701.0,32716.0,5785.0,21710.0,26143.0,11914.0
2021,150164.0,13056.0,28358.0,9119.0,5090.0,28148.0,5213.0,19849.0,27486.0,13845.0
2022,150225.0,13656.0,28195.0,9029.0,4734.0,29813.0,5153.0,19876.0,27460.0,12309.0
2023,145977.0,14683.0,30838.0,10408.0,7278.0,35125.0,6145.0,21670.0,12980.0,6850.0
2024,140419.0,14086.0,29669.0,9861.0,6898.0,31339.0,5683.0,17944.0,15783.0,9156.0

# employed_population

In [989]:
employed_population

,Көрсөткүчтөрдүн аталышы,Наименование показателей,Items,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Кыргыз Республикасы,Кыргызская Республика,Kyrgyz Republic,2277.693355,2286.4,2263.0,2302.704407,2352.100000,2363.7,2351.2,2382.5,2442.7,2445.2,2537.9,2581.1,2656.2,2756.0
1,Баткен облусу,Баткенская область,Batken oblast,165.022923,160.433783,153.4,158.555934,181.116151,186.4,184.8,178.4,175.4,165.4,176.3,177.1,168.3,170.0
2,Жалал-Абад облусу,Джалал-Абадская область,Djalal-Abad oblast,423.843932,429.544989,432.5,421.207704,408.714248,402.7,380.1,359.0,381.7,383.2,396.3,427.0,398.5,415.8
3,Ысык-Көл облусу,Иссык-Кульская область,Issyk-Kul oblast,174.881789,174.940351,163.0,166.298438,170.058722,165.2,158.2,162.9,162.2,163.7,173.5,169.9,176.5,179.6
4,Нарын облусу,Нарынская область,Naryn oblast,85.438553,85.335298,77.8,79.530871,79.151950,84.6,87.7,89.6,90.9,90.4,95.6,97.3,110.2,116.6
5,Ош облусу,Ошская область,Osh oblast,589.964334,586.947943,518.5,529.745407,543.594946,550.4,537.3,569.1,608.5,607.9,632.0,631.3,622.5,616.9
6,Талас облусу,Таласская область,Talas oblast,103.260473,102.883384,105.8,115.714272,118.600836,117.4,111.3,108.8,106.0,110.4,114.9,119.8,119.3,121.9
7,Чуй облусу,Чуйская область,Chui oblast,350.192665,353.529778,332.4,333.028401,332.336360,317.6,333.8,348.0,347.2,343.1,357.1,351.6,372.8,407.4
8,Бишкек ш.,г.Бишкек,Bishkek city,385.088686,392.781225,391.3,404.644472,424.205459,442.0,456.5,461.2,463.6,472.4,482.3,492.6,557.1,593.9
9,Ош ш.,г.Ош,Osh city,…,…,88.2,93.978908,94.294976,97.5,101.5,105.4,107.1,108.8,109.9,114.6,131.0,134.1
10,1 үй-чарбалардын бюджеттерине жана жумушчу күч...,1по данным интегрированного выборочного обслед...,1according to an integrated sample survey of h...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [990]:
clean_employed_population = employed_population.copy()

clean_employed_population = clean_employed_population.drop(columns=["Көрсөткүчтөрдүн аталышы", "Наименование показателей"])
clean_employed_population.dropna(inplace=True)
clean_employed_population = clean_employed_population.set_index('Items').T

clean_employed_population.index = pd.to_datetime(clean_employed_population.index, format='%Y').year
clean_employed_population.index.name = 'Year'

clean_employed_population.columns.name = None

# Multiply by 1000 to standardize values since metadata indicates "thousand people"
clean_employed_population = clean_employed_population * 1000

# Impute missing values for 2011 and 2012 in 'Osh city' based on 2013 value minus 6k and 3k respectively, as values show an average annual growth of 3k people
clean_employed_population.loc[2011, 'Osh city'] = clean_employed_population.loc[2013, 'Osh city'] - 6000
clean_employed_population.loc[2012, 'Osh city'] = clean_employed_population.loc[2013, 'Osh city'] - 3000

In [991]:
clean_employed_population

,Kyrgyz Republic,Batken oblast,Djalal-Abad oblast,Issyk-Kul oblast,Naryn oblast,Osh oblast,Talas oblast,Chui oblast,Bishkek city,Osh city
Year,,,,,,,,,,
2011,2277693.35495,165022.923405,423843.931881,174881.789159,85438.55271,589964.3336,103260.473241,350192.664793,385088.686161,82200.0
2012,2286400.0,160433.782836,429544.98866,174940.351004,85335.298314,586947.943188,102883.384448,353529.778276,392781.225079,85200.0
2013,2263000.0,153400.0,432500.0,163000.0,77800.0,518500.0,105800.0,332400.0,391300.0,88200.0
2014,2302704.407,158555.934,421207.704,166298.438,79530.871,529745.407,115714.272,333028.401,404644.472,93978.908
2015,2352100.0,181116.151,408714.248,170058.722,79151.95,543594.946,118600.836,332336.36,424205.459,94294.976
2016,2363700.0,186400.0,402700.0,165200.0,84600.0,550400.0,117400.0,317600.0,442000.0,97500.0
2017,2351200.0,184800.0,380100.0,158200.0,87700.0,537300.0,111300.0,333800.0,456500.0,101500.0
2018,2382500.0,178400.0,359000.0,162900.0,89600.0,569100.0,108800.0,348000.0,461200.0,105400.0
2019,2442700.0,175400.0,381700.0,162200.0,90900.0,608500.0,106000.0,347200.0,463600.0,107100.0
2020,2445200.0,165400.0,383200.0,163700.0,90400.0,607900.0,110400.0,343100.0,472400.0,108800.0
2021,2537900.0,176300.0,396300.0,173500.0,95600.0,632000.0,114900.0,357100.0,482300.0,109900.0
2022,2581100.0,177100.0,427000.0,169900.0,97300.0,631300.0,119800.0,351600.0,492600.0,114600.0
2023,2656200.0,168300.0,398500.0,176500.0,110200.0,622500.0,119300.0,372800.0,557100.0,131000.0
2024,2756000.0,170000.0,415800.0,179600.0,116600.0,616900.0,121900.0,407400.0,593900.0,134100.0

# gdp_per_capita

In [992]:
gdp_per_capita

,Көрсөткүчтөрдүн аталыштары,Наименование показателей,Items,2020,2021,2022,2023,2024
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Калктын адам башына ички дүң продукт (миң сом),Валовой внутренний продукт на душу населения (...,Gross domestic product per capita (thous. soms),95.1,114.3,146.3,187.9,219.2
2,Калктын адам башына ички дүң продукт (АКШ долл...,Валовой внутренний продукт на душу населения (...,Gross domestic product per capita (U.S. dollar),1230.3,1350.7,1740.1,2137.2,2513.4
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,*алдына ала маалыматтар,* предварительные данные,* preliminary data,NaN,NaN,NaN,NaN,NaN

In [993]:
clean_gdp_per_capita = gdp_per_capita.copy()

clean_gdp_per_capita = clean_gdp_per_capita.drop(columns=["Көрсөткүчтөрдүн аталыштары", "Наименование показателей"])
clean_gdp_per_capita.dropna(inplace=True)
clean_gdp_per_capita = clean_gdp_per_capita.set_index('Items').T

clean_gdp_per_capita.index = pd.to_datetime(clean_gdp_per_capita.index, format='%Y').year
clean_gdp_per_capita.index.name = 'Year'

clean_gdp_per_capita.columns.name = None

# Multiply by 1000 to standardize values since metadata indicates "thous. soms"
clean_gdp_per_capita["Gross domestic product per capita (thous. soms)"] = clean_gdp_per_capita['Gross domestic product per capita (thous. soms)'] * 1000

In [994]:
clean_gdp_per_capita

,Gross domestic product per capita (thous. soms),Gross domestic product per capita (U.S. dollar)
Year,,
2020,95100.0,1230.3
2021,114300.0,1350.7
2022,146300.0,1740.1
2023,187900.0,2137.2
2024,219200.0,2513.4

# monthly_salaries

In [995]:
monthly_salaries

,Көрсөткүчтөрдүн аталыштары,Наименование показателей,Items,2006,2007,2008,2009,2010,2011,2012,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Кыргыз Республикасы,Кыргызская Республика,Kyrgyz Republic,3270.0,3866.0,5378.0,6161.0,7189.0,9304.0,10726.0,...,13483.0,14847.0,15670.0,16427.0,17232.0,18940.0,19330.0,26540.0,31604.0,36047.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Баткен облусу,Баткенская область,Batken oblast,2266.0,2658.0,3703.0,4012.0,4651.0,6531.0,8206.0,...,9468.0,10093.0,10486.0,11026.0,11583.0,13017.0,13010.0,20439.0,25554.0,26662.0
4,Жалал-Абад облусу,Джалал-Абадская область,Jalal-Abat oblast,2511.0,2914.0,4467.0,5166.0,5986.0,8149.0,9818.0,...,12035.0,13277.0,13939.0,14600.0,15843.0,17580.0,17478.0,24869.0,28764.0,31229.0
5,Ысык-Көл облусу,Иссык-Кульская область,Yssyk-Kul oblast,4383.0,5048.0,6762.0,8538.0,9676.0,13667.0,14119.0,...,17979.0,19800.0,21543.0,21397.0,22208.0,26860.0,30172.0,34669.0,38743.0,41084.0
6,Нарын облусу,Нарынская область,Naryn oblast,2571.0,2853.0,4476.0,4741.0,5770.0,8445.0,9991.0,...,12724.0,13991.0,14340.0,14925.0,15945.0,18071.0,17941.0,26031.0,33011.0,35205.0
7,Ош облусу,Ошская область,Osh oblast,1569.0,2170.0,2981.0,3279.0,3719.0,6419.0,7639.0,...,8708.0,9950.0,10180.0,10307.0,11368.0,12712.0,12557.0,19762.0,23134.0,25200.0
8,Талас облусу,Таласская область,Talas oblast,1944.0,2361.0,3590.0,4412.0,5155.0,7036.0,8453.0,...,9882.0,10625.0,11295.0,12511.0,12969.0,16156.0,16400.0,25092.0,30689.0,34068.0
9,Чүй облусу,Чуйская область,Chui oblast,2858.0,3577.0,4499.0,4862.0,5736.0,7207.0,8657.0,...,11288.0,12554.0,13391.0,14114.0,14724.0,16051.0,15958.0,21641.0,25562.6,27819.0
10,Бишкек ш.,г.Бишкек,Bishkek city,4376.0,5072.0,6958.0,8041.0,9351.0,11336.0,12796.0,...,16526.0,18185.0,19336.0,20517.0,21082.0,22677.0,23085.0,30757.0,37454.7,44074.0
11,Ош ш.,г.Ош,Osh city,2733.0,3298.0,4599.0,5153.0,6104.0,7394.0,9864.0,...,11894.0,13008.0,13274.0,13804.0,14866.0,15726.0,15674.0,23459.0,26960.5,30039.0
12,*Без учета малых предприятий,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [996]:
clean_monthly_salaries = monthly_salaries.copy()

clean_monthly_salaries = clean_monthly_salaries.drop(columns=["Көрсөткүчтөрдүн аталыштары", "Наименование показателей"])
clean_monthly_salaries.dropna(inplace=True)
clean_monthly_salaries = clean_monthly_salaries.set_index('Items').T

clean_monthly_salaries.index = pd.to_datetime(clean_monthly_salaries.index, format='%Y').year
clean_monthly_salaries.index.name = 'Year'

clean_monthly_salaries.columns.name = None

# Drop rows for years 2006 to 2010
clean_monthly_salaries = clean_monthly_salaries.drop(index=[2006, 2007, 2008, 2009, 2010])

In [997]:
clean_monthly_salaries

,Kyrgyz Republic,Batken oblast,Jalal-Abat oblast,Yssyk-Kul oblast,Naryn oblast,Osh oblast,Talas oblast,Chui oblast,Bishkek city,Osh city
Year,,,,,,,,,,
2011,9304.0,6531.0,8149.0,13667.0,8445.0,6419.0,7036.0,7207.0,11336.0,7394.0
2012,10726.0,8206.0,9818.0,14119.0,9991.0,7639.0,8453.0,8657.0,12796.0,9864.0
2013,11341.0,8593.0,9993.0,15507.0,10378.0,7747.0,8829.0,9313.0,13875.0,9417.0
2014,12285.0,8903.0,10877.0,17192.0,11013.0,8141.0,9192.0,10303.0,14865.0,10578.0
2015,13483.0,9468.0,12035.0,17979.0,12724.0,8708.0,9882.0,11288.0,16526.0,11894.0
2016,14847.0,10093.0,13277.0,19800.0,13991.0,9950.0,10625.0,12554.0,18185.0,13008.0
2017,15670.0,10486.0,13939.0,21543.0,14340.0,10180.0,11295.0,13391.0,19336.0,13274.0
2018,16427.0,11026.0,14600.0,21397.0,14925.0,10307.0,12511.0,14114.0,20517.0,13804.0
2019,17232.0,11583.0,15843.0,22208.0,15945.0,11368.0,12969.0,14724.0,21082.0,14866.0
2020,18940.0,13017.0,17580.0,26860.0,18071.0,12712.0,16156.0,16051.0,22677.0,15726.0
2021,19330.0,13010.0,17478.0,30172.0,17941.0,12557.0,16400.0,15958.0,23085.0,15674.0
2022,26540.0,20439.0,24869.0,34669.0,26031.0,19762.0,25092.0,21641.0,30757.0,23459.0
2023,31604.0,25554.0,28764.0,38743.0,33011.0,23134.0,30689.0,25562.6,37454.7,26960.5
2024,36047.0,26662.0,31229.0,41084.0,35205.0,25200.0,34068.0,27819.0,44074.0,30039.0

# unemployment

In [998]:
unemployment

,Көрсөткүчтөрдүн аталыштары,Наименование показателей,Items,2006,2007,2008,2009,2010,2011,2012,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Кыргыз Республикасы,Кыргызская Республика,Kyrgyz Republic,8.3,8.2,8.2,8.415442,8.643742,8.530152,8.4,...,7.600000,7.2,6.9,6.2,5.5,5.8,5.3,4.9,4.1,3.7
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Баткен облусу,Баткенская область,Batken oblast,11.6,10.3,11.1,10.197395,10.593518,10.585734,10.8,...,10.912793,10.2,9.9,9.0,8.2,7.4,6.6,6.1,5.9,5.7
4,Жалал-Абад облусу,Джалал-Абадская область,Jalal-Abat oblast,6.4,6.8,6.9,6.960941,7.846714,8.152282,8.4,...,7.656621,7.5,7.2,6.2,5.5,11.0,11.8,10.8,8.2,7.1
5,Ысык-Көл облусу,Иссык-Кульская область,Yssyk-Kul oblast,7.7,7,7.2,9.384832,10.217816,9.65921,9.6,...,9.068651,8.9,8.7,8.4,7.9,7.4,6.3,5.5,5.1,4.5
6,Нарын облусу,Нарынская область,Naryn oblast,11,11.1,11.2,10.00545,10.344614,10.300299,10.2,...,9.286726,9.0,8.8,8.8,8.3,7.3,6.3,5.8,5.1,4.8
7,Ош облусу,Ошская область,Osh oblast,5,5.4,5.5,6.631339,6.627287,6.630795,6.8,...,6.027853,5.5,5.1,4.2,3.5,2.6,1.9,1.5,1.4,0.9
8,Талас облусу,Таласская область,Talas oblast,5.1,5.1,5.4,4.902786,5.060168,5.043066,4.1,...,3.259938,2.8,2.5,2.5,2.5,2.6,2.6,2.3,2.0,2.0
9,Чүй облусу,Чуйская область,Chui oblast,13.1,13,12.7,10.349741,10.24284,9.919452,9.9,...,8.592704,8.4,8.1,7.3,6.6,6.1,5.3,4.6,4.1,3.7
10,Бишкек ш.,г.Бишкек,Bishkek city,9.3,8.7,8.6,10.154086,9.994021,9.579866,8.7,...,8.053710,7.7,7.3,6.6,5.9,5.0,4.1,4.0,3.5,3.5
11,Ош ш.,г.Ош,Osh city,…,…,…,…,…,…,…,...,3.903298,3.6,3.5,3.0,2.4,2.8,2.8,2.6,2.1,1.9
12,1үй-чарбалардын бюджеттерине жана жумушчу күчү...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1 По данным интегрированного выборочного обс...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1Аccording to an integrated sample survey of h...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [999]:
clean_unemployment = unemployment.copy()

clean_unemployment = clean_unemployment.drop(columns=["Көрсөткүчтөрдүн аталыштары", "Наименование показателей"])
clean_unemployment.dropna(inplace=True)
clean_unemployment = clean_unemployment.set_index('Items').T

clean_unemployment.index = pd.to_datetime(clean_unemployment.index, format='%Y').year
clean_unemployment.index.name = 'Year'

clean_unemployment.columns.name = None

# Convert all columns to float, handling non-numeric values
clean_unemployment = clean_unemployment.apply(pd.to_numeric, errors='coerce')

# Convert percentage values to proportions
clean_unemployment = clean_unemployment / 100

clean_unemployment = clean_unemployment.drop(index=[2006, 2007, 2008, 2009, 2010])

# Impute missing values for Osh city based on trend
# Trend of unemployment decreasing by 0.003 each year
clean_unemployment.loc[2011, 'Osh city'] = clean_unemployment.loc[2013, 'Osh city'] + 0.006
clean_unemployment.loc[2012, 'Osh city'] = clean_unemployment.loc[2013, 'Osh city'] + 0.003

In [1000]:
clean_unemployment

,Kyrgyz Republic,Batken oblast,Jalal-Abat oblast,Yssyk-Kul oblast,Naryn oblast,Osh oblast,Talas oblast,Chui oblast,Bishkek city,Osh city
Year,,,,,,,,,,
2011,0.085302,0.105857,0.081523,0.096592,0.103003,0.066308,0.050431,0.099195,0.095799,0.052000
2012,0.084000,0.108000,0.084000,0.096000,0.102000,0.068000,0.041000,0.099000,0.087000,0.049000
2013,0.083000,0.127000,0.082000,0.095000,0.091000,0.063000,0.037000,0.097000,0.094000,0.046000
2014,0.080000,0.126000,0.076000,0.093000,0.097000,0.066000,0.039000,0.089000,0.089000,0.042000
2015,0.076000,0.109128,0.076566,0.090687,0.092867,0.060279,0.032599,0.085927,0.080537,0.039033
2016,0.072000,0.102000,0.075000,0.089000,0.090000,0.055000,0.028000,0.084000,0.077000,0.036000
2017,0.069000,0.099000,0.072000,0.087000,0.088000,0.051000,0.025000,0.081000,0.073000,0.035000
2018,0.062000,0.090000,0.062000,0.084000,0.088000,0.042000,0.025000,0.073000,0.066000,0.030000
2019,0.055000,0.082000,0.055000,0.079000,0.083000,0.035000,0.025000,0.066000,0.059000,0.024000
2020,0.058000,0.074000,0.110000,0.074000,0.073000,0.026000,0.026000,0.061000,0.050000,0.028000
2021,0.053000,0.066000,0.118000,0.063000,0.063000,0.019000,0.026000,0.053000,0.041000,0.028000
2022,0.049000,0.061000,0.108000,0.055000,0.058000,0.015000,0.023000,0.046000,0.040000,0.026000
2023,0.041000,0.059000,0.082000,0.051000,0.051000,0.014000,0.020000,0.041000,0.035000,0.021000
2024,0.037000,0.057000,0.071000,0.045000,0.048000,0.009000,0.020000,0.037000,0.035000,0.019000

# production

In [1001]:
production

,Көрсөткүчтөрдүн аталыштары,Наименование показателей,Items,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Кыргыз Республикасы,Кыргызская Республика,Kyrgyz Republic,164361.1,137229.2,169829.4,171108.9,181026.7,209812.0000,237225.3,257348.5,283971.7079,325090.1,370533.8,435815.6,495344.0,599755.2
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Баткен облусу,Баткенская область,Batken oblast,3536.7,4545.4,5929.7,5284.1,4821.6,4359.2825,4744.5,2810.9,2975.2513,3110.9,4349.4,4741.7,6428.9,9100.3
3,Жалал-Абад облусу,Джалал-Абадская область,Djalal-Abad oblast,14325.3,15468.9,13033.2,13300.1,18115.1,20087.8535,25006.5,26808.0,28711.3886,28306.0,36609.2,45724.3,51861.7,58354.1
4,Ыссык-Көл облусу,Ыссык-Кульская область,Issyk-Kul oblast,44257.9,27232.2,41723.6,40993.1,42198.1,51129.4198,52416.4,49965.4,62280.2412,78831.2,74737.6,87613.5,81350.6,96703.6
5,Нарын облусу,Нарынская область,Naryn oblast,1177.2,1245.2,1257.9,1590.7,1977.7,2332.3707,2388.2,2622.8,2870.4549,3206.6,3293.6,4322.8,4965.0,7028.6
6,Ош облусу,Ошская область,Osh oblast,2852.3,3006.0,3389.0,3581.3,3735.8,4074.7310,4772.2,9621.1,10385.5737,9457.8,13516.8,14596.5,17317.6,18474.2
7,Талас облусу,Таласская область,Talas oblast,750.5,773.0,844.0,981.1,895.9,949.0357,1316.7,1290.9,1578.3340,1899.9,15128.8,22789.9,26240.3,34164.8
8,Чүй облусу,Чуйская область,Chui oblast,65011.2,49000.7,67331.9,67873.8,70836.5,86977.5784,102403.7,116570.2,128102.5328,155656.3,167981.4,192441.8,222615.1,258345.1
9,Бишкек ш.,г. Бишкек,Bishkek Сity,30269.4,33454.8,33743.9,34639.4,35081.7,36458.3747,39876.9,42840.7,42291.9887,40053.9,48978.7,57148.9,77162.4,106682.8
10,Ош ш.,г. Ош,Osh Сity,2180.6,2503.0,2576.2,2865.3,3364.3,3443.3136,4300.2,4818.5,4775.9427,4567.5,5938.3,6436.2,7402.4,10901.7

In [1002]:
clean_production = production.copy()

clean_production = clean_production.drop(columns=["Көрсөткүчтөрдүн аталыштары", "Наименование показателей"])
clean_production.dropna(inplace=True)
clean_production = clean_production.set_index('Items').T

clean_production.index = pd.to_datetime(clean_production.index, format='%Y').year
clean_production.index.name = 'Year'

clean_production.columns.name = None

# Convert to millions based on metadata
clean_production = clean_production * 1000000

In [1003]:
clean_production

,Kyrgyz Republic,Batken oblast,Djalal-Abad oblast,Issyk-Kul oblast,Naryn oblast,Osh oblast,Talas oblast,Chui oblast,Bishkek Сity,Osh Сity
Year,,,,,,,,,,
2011,1.643611e+11,3.536700e+09,1.432530e+10,4.425790e+10,1.177200e+09,2.852300e+09,7.505000e+08,6.501120e+10,3.026940e+10,2.180600e+09
2012,1.372292e+11,4.545400e+09,1.546890e+10,2.723220e+10,1.245200e+09,3.006000e+09,7.730000e+08,4.900070e+10,3.345480e+10,2.503000e+09
2013,1.698294e+11,5.929700e+09,1.303320e+10,4.172360e+10,1.257900e+09,3.389000e+09,8.440000e+08,6.733190e+10,3.374390e+10,2.576200e+09
2014,1.711089e+11,5.284100e+09,1.330010e+10,4.099310e+10,1.590700e+09,3.581300e+09,9.811000e+08,6.787380e+10,3.463940e+10,2.865300e+09
2015,1.810267e+11,4.821600e+09,1.811510e+10,4.219810e+10,1.977700e+09,3.735800e+09,8.959000e+08,7.083650e+10,3.508170e+10,3.364300e+09
2016,2.098120e+11,4.359282e+09,2.008785e+10,5.112942e+10,2.332371e+09,4.074731e+09,9.490357e+08,8.697758e+10,3.645837e+10,3.443314e+09
2017,2.372253e+11,4.744500e+09,2.500650e+10,5.241640e+10,2.388200e+09,4.772200e+09,1.316700e+09,1.024037e+11,3.987690e+10,4.300200e+09
2018,2.573485e+11,2.810900e+09,2.680800e+10,4.996540e+10,2.622800e+09,9.621100e+09,1.290900e+09,1.165702e+11,4.284070e+10,4.818500e+09
2019,2.839717e+11,2.975251e+09,2.871139e+10,6.228024e+10,2.870455e+09,1.038557e+10,1.578334e+09,1.281025e+11,4.229199e+10,4.775943e+09
2020,3.250901e+11,3.110900e+09,2.830600e+10,7.883120e+10,3.206600e+09,9.457800e+09,1.899900e+09,1.556563e+11,4.005390e+10,4.567500e+09
2021,3.705338e+11,4.349400e+09,3.660920e+10,7.473760e+10,3.293600e+09,1.351680e+10,1.512880e+10,1.679814e+11,4.897870e+10,5.938300e+09
2022,4.358156e+11,4.741700e+09,4.572430e+10,8.761350e+10,4.322800e+09,1.459650e+10,2.278990e+10,1.924418e+11,5.714890e+10,6.436200e+09
2023,4.953440e+11,6.428900e+09,5.186170e+10,8.135060e+10,4.965000e+09,1.731760e+10,2.624030e+10,2.226151e+11,7.716240e+10,7.402400e+09
2024,5.997552e+11,9.100300e+09,5.835410e+10,9.670360e+10,7.028600e+09,1.847420e+10,3.416480e+10,2.583451e+11,1.066828e+11,1.090170e+10

# educational_facilities

In [1004]:
educational_facilities

,Көрсөткүчтөрдүн аталышы,Наименование показателей,Items,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Мектепке чейинки уюмдар,Дошкольные организации,Pre-school institutions,741,819,927,1062,1186,1296,1390,1497,1617,1648,1712,1834,1912,1997
1,Жалпы билим берүү уюмдары,Общеобразовательные организации,General education schools,2204,2201,2207,2205,2218,2236,2262,2265,2283,2296,2333,2350,2377,2394
2,Башталгыч (1 - 4-класстар),Начальные (1 - 4 классы),Elementary (1 - 4 grades),125,118,115,115,115,122,132,130,131,133,135,135,133,130
3,Негизги (1 - 9-класстар),Основные (1 - 9 классы),Junior (5 - 9 grades),202,222,202,203,200,196,192,195,201,199,210,224,227,242
4,Орто (1 - 11-класстар),Средние (1 - 11 классы),High (10 - 11 grades),1857,1841,1871,1868,1884,1900,1920,1922,1931,1946,1970,1973,1999,2004
5,Атайын муктаждыгы бар балдар,Для детей со специальными нуждами,For children with learning disabilities,20,20,19,19,19,18,18,18,20,18,18,18,18,18
6,Башталгыч кесиптик билим берүү уюмдары,Образовательные организации начального профес...,Vocational schools,109,110,110,101,101,101,99,99,99,99,99,100,100,98
7,Орто кесиптик билим берүү уюмдары,Образовательные организации среднего професси...,Secondary special educational institutions,126,132,131,129,130,139,145,148,144,138,141,142,135,134
8,Жогорку кесиптик билим берүү уюмдары,Образовательные организации высшего профессио...,Higher educational institutions,54,54,55,53,52,50,51,51,55,57,60,61,58,57

In [1005]:
clean_educational_facilities = educational_facilities.copy()

clean_educational_facilities = clean_educational_facilities.drop(columns=["Көрсөткүчтөрдүн аталышы", "Наименование показателей"])
clean_educational_facilities = clean_educational_facilities.set_index('Items').T

clean_educational_facilities.index = pd.to_datetime(clean_educational_facilities.index, format='%Y').year
clean_educational_facilities.index.name = 'Year'

clean_educational_facilities.columns.name = None

In [1006]:
clean_educational_facilities

,Pre-school institutions,General education schools,Elementary (1 - 4 grades),Junior (5 - 9 grades),High (10 - 11 grades),For children with learning disabilities,Vocational schools,Secondary special educational institutions,Higher educational institutions
Year,,,,,,,,,
2011,741,2204,125,202,1857,20,109,126,54
2012,819,2201,118,222,1841,20,110,132,54
2013,927,2207,115,202,1871,19,110,131,55
2014,1062,2205,115,203,1868,19,101,129,53
2015,1186,2218,115,200,1884,19,101,130,52
2016,1296,2236,122,196,1900,18,101,139,50
2017,1390,2262,132,192,1920,18,99,145,51
2018,1497,2265,130,195,1922,18,99,148,51
2019,1617,2283,131,201,1931,20,99,144,55
2020,1648,2296,133,199,1946,18,99,138,57
2021,1712,2333,135,210,1970,18,99,141,60
2022,1834,2350,135,224,1973,18,100,142,61
2023,1912,2377,133,227,1999,18,100,135,58
2024,1997,2394,130,242,2004,18,98,134,57

# instructors

In [1007]:
instructors

,Көрсөткүчтөрдүн аталышы,Наименование показателей,Items,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Мектепке чейинки уюмдар,Дошкольные организации,Pre-school institutions,3647,4053,4492,5116,5693,6414,7151,7694,8312,8301,8785,9796,10426,11959
1,Жалпы билим беруучу уюмдар,Общеобразовательные организации,General education schools,75502,75656,74407,72928,75529,79472,80773,77639,78552,82055,82724,89962,93531,93696
2,Атайын муктаждыгы бар балдар учун,Для детей со специальными нуждами,For children with learning disabilities,660,606,472,510,497,516,519,509,518,541,536,569,577,568
3,Баштапкы кесиптик билим берүү уюмдары,Образовательные организации начального профес...,Vocational schools,3875,3811,3293,3404,3448,3584,3520,3079,3311,3418,3477,3140,3182,3631
4,Орто кесиптик билим берүү уюмдары,Образовательные организации среднего професси...,Secondary special educational institutions,5590,6343,7230,7547,6725,7427,7496,7179,7181,7299,7857,8447,8684,9550
5,Жогорку кесиптик билим беріі уюмдары,Образовательные организации высшего профессио...,Higher educational institutions,12830,12633,14059,13155,14233,10812,12145,11665,12160,12197,13006,12039,12322,12570

In [1009]:
clean_instructors = instructors.copy()

clean_instructors = clean_instructors.drop(columns=["Көрсөткүчтөрдүн аталышы    ", "Наименование показателей"])
clean_instructors = clean_instructors.set_index('Items').T

clean_instructors.index = pd.to_datetime(clean_instructors.index, format='%Y').year
clean_instructors.index.name = 'Year'

clean_instructors.columns.name = None

In [1010]:
clean_instructors

,Pre-school institutions,General education schools,For children with learning disabilities,Vocational schools,Secondary special educational institutions,Higher educational institutions
Year,,,,,,
2011,3647,75502,660,3875,5590,12830
2012,4053,75656,606,3811,6343,12633
2013,4492,74407,472,3293,7230,14059
2014,5116,72928,510,3404,7547,13155
2015,5693,75529,497,3448,6725,14233
2016,6414,79472,516,3584,7427,10812
2017,7151,80773,519,3520,7496,12145
2018,7694,77639,509,3079,7179,11665
2019,8312,78552,518,3311,7181,12160
2020,8301,82055,541,3418,7299,12197
2021,8785,82724,536,3477,7857,13006
2022,9796,89962,569,3140,8447,12039
2023,10426,93531,577,3182,8684,12322
2024,11959,93696,568,3631,9550,12570